[build]
  command = "npm run build"
  publish = "dist"
  functions = "" # Forces Netlify to ignore config files as serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200